export let groceryItems = [
    { id: 1, name: "Apples", checked: false, quantity: 1 },
    { id: 2, name: "Bananas", checked: false, quantity: 1 },
    { id: 3, name: "Carrots", checked: true, quantity: 1 },
    { id: 4, name: "Bread", checked: false, quantity: 1 },
    { id: 5, name: "Milk", checked: false, quantity: 3 },
    { id: 6, name: "Eggs", checked: false, quantity: 1 },
    { id: 7, name: "Chicken", checked: false, quantity: 1 },
    { id: 8, name: "Rice", checked: false, quantity: 1 },
    { id: 9, name: "Pasta", checked: false, quantity: 1 },
    { id: 10, name: "Tomatoes", checked: false, quantity: 1 },
    { id: 11, name: "Spinach", checked: false, quantity: 1 },
    { id: 12, name: "Cheese", checked: false, quantity: 1 },
    { id: 13, name: "Yogurt", checked: false, quantity: 1 },
    { id: 14, name: "Orange Juice", checked: false, quantity: 1 },
    { id: 15, name: "Coffee", checked: false, quantity: 1 },
    { id: 16, name: "Butter", checked: false, quantity: 1 },
    { id: 17, name: "Potatoes", checked: false, quantity: 1 },
    { id: 18, name: "Onions", checked: false, quantity: 1 },
    { id: 19, name: "Garlic", checked: false, quantity: 1 },
    { id: 20, name: "Peanut Butter", checked: false, quantity: 1 }
]